module.exports = {
  name: "invoices",
  attributes: [
    {
      key: "remote_id",
      type: "string",
      required: false,
      array: false,
      size: 100,
      default: null,
    },
    {
      key: "currency",
      type: "string",
      required: false,
      array: false,
      elements: ["UGX", "KSH", "USD", "GBP"],
      format: "enum",
      default: "UGX",
    },
    {
      key: "title",
      type: "string",
      required: true,
      array: false,
      size: 100,
      default: null,
    },
    {
      key: "issue_date",
      type: "datetime",
      required: false,
      array: false,
      format: "",
      default: null,
    },
    {
      key: "due_date",
      type: "datetime",
      required: false,
      array: false,
      format: "",
      default: null,
    },
    {
      key: "sub_total",
      type: "double",
      required: false,
      array: false,
      min: 0,
      max: 1.7976931348623157e308,
      default: null,
    },
    {
      key: "discount",
      type: "double",
      required: false,
      array: false,
      min: 0,
      max: 1.7976931348623157e308,
      default: null,
    },
    {
      key: "tax",
      type: "double",
      required: false,
      array: false,
      min: 0,
      max: 1.7976931348623157e308,
      default: null,
    },
    {
      key: "shipping",
      type: "double",
      required: false,
      array: false,
      min: 0,
      max: 1.7976931348623157e308,
      default: null,
    },
    {
      key: "amount_due",
      type: "double",
      required: false,
      array: false,
      min: 0,
      max: 1.7976931348623157e308,
      default: null,
    },
    {
      key: "amount_paid",
      type: "double",
      required: false,
      array: false,
      min: 0,
      max: 1.7976931348623157e308,
      default: null,
    },
    {
      key: "balance_due",
      type: "double",
      required: false,
      array: false,
      min: 0,
      max: 1.7976931348623157e308,
      default: null,
    },
    {
      key: "notes",
      type: "string",
      required: false,
      array: false,
      size: 4000,
      default: null,
    },
    {
      key: "terms",
      type: "string",
      required: false,
      array: false,
      size: 4000,
      default: null,
    },
    {
      key: "logo",
      type: "string",
      required: false,
      array: false,
      size: 1073741824,
      default: null,
    },
    {
      key: "paper_size",
      type: "string",
      required: false,
      array: false,
      elements: ["a6", "a5", "a4", "letter"],
      format: "enum",
      default: "a4",
    },
    {
      key: "orientation",
      type: "string",
      required: false,
      array: false,
      elements: ["portrait", "landscape"],
      format: "enum",
      default: null,
    },
    {
      key: "status",
      type: "string",
      required: false,
      array: false,
      elements: [
        "draft",
        "sent",
        "viewed",
        "partial",
        "paid",
        "overdue",
        "void",
        "disputed",
        "refunded",
        "unpaid",
      ],
      format: "enum",
      default: "unpaid",
    },
    {
      key: "created_by",
      type: "string",
      required: false,
      array: false,
      size: 50,
      default: null,
    },
    {
      key: "invoice_no",
      type: "string",
      required: true,
      array: false,
      size: 100,
      default: null,
    },
    {
      key: "payment_date",
      type: "datetime",
      required: false,
      array: false,
      format: "",
      default: null,
    },
    // Relationships
    {
      key: "items",
      type: "relationship",
      required: false,
      array: false,
      relatedCollection: "items",
      relationType: "oneToMany",
      twoWay: false,
      onDelete: "cascade",
      side: "parent",
    },
    {
      key: "billed_from",
      type: "relationship",
      required: false,
      array: false,
      relatedCollection: "billing-address",
      relationType: "oneToOne",
      twoWay: false,
      onDelete: "cascade",
      side: "parent",
    },
    {
      key: "billed_to",
      type: "relationship",
      required: false,
      array: false,
      relatedCollection: "billing-address",
      relationType: "oneToOne",
      twoWay: false,
      onDelete: "cascade",
      side: "parent",
    },
  ],
  indexes: [
    {
      key: "invoice_no",
      type: "unique",
      status: "available",
      attributes: ["invoice_no"],
      orders: ["ASC"],
    },
  ],
};
